//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev_App_Financeiro.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dev_App_Financeiro.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras de Negócio:
        ///
        ///1) A lista de fornecedores sera filtrada pelo arquivo de movimentações. Assim, somente os fornecedores que forem encontrados no arquivo de movimentações serão convertidos.
        ///
        ///2) Quando o código do país for diferente de &quot;BR&quot; na origem, o campo &quot;CNPJ/CPF/Livre&quot; no destino será preenchido com o campo &quot;Apelido&quot; do arquivo de fornecedores.
        ///
        ///	2.1) Se o campo &quot;Apelido&quot; na origem tiver o tamanho igual a 6, a letra &quot;L&quot; é adicionada ao valor do campo conforme regra do PROSOFT.
        ///
        ///3) Quando o c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpConverteFornecedor {
            get {
                return ResourceManager.GetString("HelpConverteFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regras de Negócio:
        ///
        ///1) Quando houver mais de 200 lançamentos em uma única movimentação, a movimentação será dividida em lançamentos a cada 199 registros e um lançamento compensatório será informado na conta de compensação informada no arquivo de configuração de lançamentos.
        ///
        ///2) Quando o código do país for diferente de &quot;BR&quot; na origem, o campo &quot;CNPJ/CPF/Livre&quot; no destino será preenchido com o campo &quot;Apelido&quot; do arquivo de fornecedores.
        ///
        ///	2.1) Se o campo &quot;Apelido&quot; na origem tiver o tamanho igual a 6, a l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpConverteMovimentacao {
            get {
                return ResourceManager.GetString("HelpConverteMovimentacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_help {
            get {
                object obj = ResourceManager.GetObject("ico_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOGO_El_Cano_solo_banderas_ {
            get {
                object obj = ResourceManager.GetObject("LOGO_El_Cano_solo_banderas_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoSegInfo {
            get {
                object obj = ResourceManager.GetObject("logoSegInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
